export const POPULAR_VIDEO = [
  {
    kind: 'youtube#video',
    etag: '18fRfls47dsiiUt2-XiZ7CMtsk8',
    id: '8OXlDMNRu_Q',
    snippet: {
      publishedAt: '2021-08-09T17:00:10Z',
      channelId: 'UC47kJWRBD-NREBvmBg5kWeA',
      title: 'King Von - Demon (Official Video)',
      description:
        'From the album "Welcome to O\'Block". Out now! \nStream: https://music.empi.re/oblock\n\n#KingVon #WelcomeToOblock #OnlyTheFamilyEntertainment\n\nFollow King Von:\nhttps://www.instagram.com/kingvonfrmdao\nhttps://twitter.com/KingVonFrmdaWic\n\nSubscribe to King Von\'s official channel for exclusive music videos and behind the scenes looks: http://bit.ly/Subscribe-to-King-Von\n\nOfficial audio by King Von from the album "Welcome to O\'Block" © 2020 Only The Family Entertainment / EMPIRE',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/8OXlDMNRu_Q/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/8OXlDMNRu_Q/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/8OXlDMNRu_Q/hqdefault.jpg',
          width: 480,
          height: 360,
        },
      },
      channelTitle: 'King Von',
      tags: [
        'King Von',
        'Demon (Official Video)',
        'Only The Family Entertainment / EMPIRE',
        'EMPIRE',
      ],
      categoryId: '10',
      liveBroadcastContent: 'none',
      localized: {
        title: 'King Von - Demon (Official Video)',
        description:
          'From the album "Welcome to O\'Block". Out now! \nStream: https://music.empi.re/oblock\n\n#KingVon #WelcomeToOblock #OnlyTheFamilyEntertainment\n\nFollow King Von:\nhttps://www.instagram.com/kingvonfrmdao\nhttps://twitter.com/KingVonFrmdaWic\n\nSubscribe to King Von\'s official channel for exclusive music videos and behind the scenes looks: http://bit.ly/Subscribe-to-King-Von\n\nOfficial audio by King Von from the album "Welcome to O\'Block" © 2020 Only The Family Entertainment / EMPIRE',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'bq8hUd4Dhx5JiiTRkwEGWhN0-LE',
    id: 'foeMkH9UH88',
    snippet: {
      publishedAt: '2021-08-09T16:00:18Z',
      channelId: 'UCke6I9N4KfC968-yRcd5YRg',
      title: '*PLAYSTATION 5* Mod in Among Us',
      description:
        'We add an Playstation Imposter in Among Us!\n\n🔔 Subscribe & click the bell!  https://www.youtube.com/user/SSundee?sub_confirmation=1\n👍 Hit the Thumbs Up if you liked this video! \n\n🤖 My Friends! 🤖\n@Nicovald \n@Sigils \n@Henwy \n@Biffle \n@Lookumz \n@Zud \n@LoafX \n@helloiamkate \n@PatP \n\nMod Maker Phil: https://www.youtube.com/channel/UCPHsF_J57xv4H-StZfKrVfQ\n\n❗️ Follow Me! ❗️\nTwitter: https://www.twitter.com/SSundee\nDiscord: https://discord.gg/SSundee\nInstagram: https://instagram.com/ssundeeyt\nFacebook:  https://www.facebook.com/pages/SSundee/200010033358843\n\n👨🏻‍🍳 Awesome Video Editor ► Luke\nhttps://www.youtube.com/channel/UCguIgCWjfgioh8okSzd_Xhg?view_as=subscriber\n\n👨🏼‍🎨 Awesome Thumbnail Maker ► Flash\nhttps://www.youtube.com/channel/UCLy01oVLarj7RNQm52jnGKw\n\n🎨 Awesome Animator ► David\nhttps://www.youtube.com/channel/UCxSSIQevKsx2bFc_Gn4WAMg?view_as=subscriber\n\n🎶 Music by Ninety9 ► LivesTobu - Such Fun\nVideo Link: https://www.youtube.com/watch?v=d3Oc26AFDdU\nChannel: https://99l.tv/Subscribe\nDownload the album! https://99l.tv/Levelup-i\n\nThanks for watching!',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/foeMkH9UH88/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/foeMkH9UH88/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/foeMkH9UH88/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/foeMkH9UH88/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/foeMkH9UH88/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'SSundee',
      categoryId: '20',
      liveBroadcastContent: 'none',
      localized: {
        title: '*PLAYSTATION 5* Mod in Among Us',
        description:
          'We add an Playstation Imposter in Among Us!\n\n🔔 Subscribe & click the bell!  https://www.youtube.com/user/SSundee?sub_confirmation=1\n👍 Hit the Thumbs Up if you liked this video! \n\n🤖 My Friends! 🤖\n@Nicovald \n@Sigils \n@Henwy \n@Biffle \n@Lookumz \n@Zud \n@LoafX \n@helloiamkate \n@PatP \n\nMod Maker Phil: https://www.youtube.com/channel/UCPHsF_J57xv4H-StZfKrVfQ\n\n❗️ Follow Me! ❗️\nTwitter: https://www.twitter.com/SSundee\nDiscord: https://discord.gg/SSundee\nInstagram: https://instagram.com/ssundeeyt\nFacebook:  https://www.facebook.com/pages/SSundee/200010033358843\n\n👨🏻‍🍳 Awesome Video Editor ► Luke\nhttps://www.youtube.com/channel/UCguIgCWjfgioh8okSzd_Xhg?view_as=subscriber\n\n👨🏼‍🎨 Awesome Thumbnail Maker ► Flash\nhttps://www.youtube.com/channel/UCLy01oVLarj7RNQm52jnGKw\n\n🎨 Awesome Animator ► David\nhttps://www.youtube.com/channel/UCxSSIQevKsx2bFc_Gn4WAMg?view_as=subscriber\n\n🎶 Music by Ninety9 ► LivesTobu - Such Fun\nVideo Link: https://www.youtube.com/watch?v=d3Oc26AFDdU\nChannel: https://99l.tv/Subscribe\nDownload the album! https://99l.tv/Levelup-i\n\nThanks for watching!',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'Luw0RWHLGuqzx-Lvv6esh1JIbO0',
    id: '3MLjfnouo88',
    snippet: {
      publishedAt: '2021-08-09T03:21:33Z',
      channelId: 'UCvfat4DPrM3BM-xZ2zn5ruQ',
      title: 'NoCap - Vaccine (Official Music Video)',
      description:
        'NoCap - Vaccine\nDirected by TeoShotThis\n\nThe Hood Dictionary - Stream/Download: https://NoCap.lnk.to/TheHoodDictionaryID\nThe Backend Child - Stream/Download: https://NoCap.lnk.to/TheBackendChildID\n\nSubscribe for more official content from NoCap: \nhttps://nocap.lnk.to/YouTubeAY\n\nNeighborhood Hero - Stream/Download Now: https://NoCap.lnk.to/NeighorhoodHeroID\n\nRogerville - Stream/Download Now: https://NoCap.lnk.to/RogervilleID\n\nFollow NoCap:\nhttp://instagram.com/thebackendchild \nhttps://twitter.com/NoCap\nhttps://soundcloud.com/officialnocap\nhttps://www.facebook.com/NoCapOfficial',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/3MLjfnouo88/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/3MLjfnouo88/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/3MLjfnouo88/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/3MLjfnouo88/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/3MLjfnouo88/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'NoCap',
      tags: [
        'nocap',
        'thebackendchild',
        'ghetto angels',
        'legend',
        'point guard',
        'rylo rodriguez',
        'rylo',
        'free ghetto',
        'blind nights',
        'freestyle',
        'mobile',
        'alabama',
        'innocent',
        'nba youngboy',
        'quando rondo',
        'evol',
        'exotic',
        'lyrics',
        'rap lyrics',
        'official',
        'official video',
        'official audio',
      ],
      categoryId: '10',
      liveBroadcastContent: 'none',
      localized: {
        title: 'NoCap - Vaccine (Official Music Video)',
        description:
          'NoCap - Vaccine\nDirected by TeoShotThis\n\nThe Hood Dictionary - Stream/Download: https://NoCap.lnk.to/TheHoodDictionaryID\nThe Backend Child - Stream/Download: https://NoCap.lnk.to/TheBackendChildID\n\nSubscribe for more official content from NoCap: \nhttps://nocap.lnk.to/YouTubeAY\n\nNeighborhood Hero - Stream/Download Now: https://NoCap.lnk.to/NeighorhoodHeroID\n\nRogerville - Stream/Download Now: https://NoCap.lnk.to/RogervilleID\n\nFollow NoCap:\nhttp://instagram.com/thebackendchild \nhttps://twitter.com/NoCap\nhttps://soundcloud.com/officialnocap\nhttps://www.facebook.com/NoCapOfficial',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: '4LeQdT3I2yvq0sRtt5rP6dbENcw',
    id: 'hxwpkM5w3Cc',
    snippet: {
      publishedAt: '2021-08-07T23:00:03Z',
      channelId: 'UCX6OQ3DkcsbYNE6H8uQQuVA',
      title: 'I Got Hunted By The FBI',
      description:
        'You guys loved the bounty hunter video so we did it with the FBI, i hope you enjoy!\nGet $5 on Venmo just for adding Honey ▸ https://joinhoney.com/mrbeast5\nThanks to Honey for sponsoring this video!\nTerms Apply. Offer can be modified or terminated at any time. Limited to the first 20k people\nNew Merch - https://shopmrbeast.com/\n\nSUBSCRIBE OR I TAKE YOUR DOG\n╔═╦╗╔╦╗╔═╦═╦╦╦╦╗╔═╗\n║╚╣║║║╚╣╚╣╔╣╔╣║╚╣═╣ \n╠╗║╚╝║║╠╗║╚╣║║║║║═╣\n╚═╩══╩═╩═╩═╩╝╚╩═╩═╝\n\n----------------------------------------------------------------\nfollow all of these or i will kick you\n• Facebook - https://www.facebook.com/MrBeast6000/\n• Twitter - https://twitter.com/MrBeast\n•  Instagram - https://www.instagram.com/mrbeast\n--------------------------------------------------------------------',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/hxwpkM5w3Cc/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/hxwpkM5w3Cc/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/hxwpkM5w3Cc/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/hxwpkM5w3Cc/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/hxwpkM5w3Cc/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'MrBeast',
      categoryId: '24',
      liveBroadcastContent: 'none',
      localized: {
        title: 'I Got Hunted By The FBI',
        description:
          'You guys loved the bounty hunter video so we did it with the FBI, i hope you enjoy!\nGet $5 on Venmo just for adding Honey ▸ https://joinhoney.com/mrbeast5\nThanks to Honey for sponsoring this video!\nTerms Apply. Offer can be modified or terminated at any time. Limited to the first 20k people\nNew Merch - https://shopmrbeast.com/\n\nSUBSCRIBE OR I TAKE YOUR DOG\n╔═╦╗╔╦╗╔═╦═╦╦╦╦╗╔═╗\n║╚╣║║║╚╣╚╣╔╣╔╣║╚╣═╣ \n╠╗║╚╝║║╠╗║╚╣║║║║║═╣\n╚═╩══╩═╩═╩═╩╝╚╩═╩═╝\n\n----------------------------------------------------------------\nfollow all of these or i will kick you\n• Facebook - https://www.facebook.com/MrBeast6000/\n• Twitter - https://twitter.com/MrBeast\n•  Instagram - https://www.instagram.com/mrbeast\n--------------------------------------------------------------------',
      },
      defaultAudioLanguage: 'en-US',
    },
  },
  {
    kind: 'youtube#video',
    etag: '0yzA6aIsN5LJSaWuiSAfXA1-XoQ',
    id: 'TiVrW-5eqUU',
    snippet: {
      publishedAt: '2021-08-09T00:36:12Z',
      channelId: 'UCDVYQ4Zhbm3S2dlz7P1GBDg',
      title:
        'Peyton Manning Full Hall of Fame Speech | 2021 Pro Football Hall of Fame | NFL',
      description:
        'Subscribe to NFL: http://j.mp/1L0bVBu\nCheck out our other channels:\nPara más contenido de la NFL en Español, suscríbete a https://www.youtube.com/nflenespanol\nNFL Fantasy Football https://www.youtube.com/nflfantasyfootball\nNFL Vault http://www.youtube.com/nflvault\nNFL Network http://www.youtube.com/nflnetwork\nNFL Films http://www.youtube.com/nflfilms\nNFL Rush http://www.youtube.com/nflrush\nNFL Play Football https://www.youtube.com/playfootball\nNFL Podcasts https://www.youtube.com/nflpodcasts\n#NFL #Football #AmericanFootball',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/TiVrW-5eqUU/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/TiVrW-5eqUU/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/TiVrW-5eqUU/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/TiVrW-5eqUU/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/TiVrW-5eqUU/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'NFL',
      categoryId: '17',
      liveBroadcastContent: 'none',
      localized: {
        title:
          'Peyton Manning Full Hall of Fame Speech | 2021 Pro Football Hall of Fame | NFL',
        description:
          'Subscribe to NFL: http://j.mp/1L0bVBu\nCheck out our other channels:\nPara más contenido de la NFL en Español, suscríbete a https://www.youtube.com/nflenespanol\nNFL Fantasy Football https://www.youtube.com/nflfantasyfootball\nNFL Vault http://www.youtube.com/nflvault\nNFL Network http://www.youtube.com/nflnetwork\nNFL Films http://www.youtube.com/nflfilms\nNFL Rush http://www.youtube.com/nflrush\nNFL Play Football https://www.youtube.com/playfootball\nNFL Podcasts https://www.youtube.com/nflpodcasts\n#NFL #Football #AmericanFootball',
      },
    },
  },
  {
    kind: 'youtube#video',
    etag: 'sSKa_HzPH53sRsxERPq16DPk0bc',
    id: 'IGf9jAank64',
    snippet: {
      publishedAt: '2021-08-08T18:04:37Z',
      channelId: 'UCGwu0nbY2wSkW8N-cghnLpA',
      title: 'Amazing Island: The Game You Wish You Played',
      description:
        "shaped like friends\n\n\nAlpharad: https://www.youtube.com/user/alpharadd\nScribbleShowdown tickets: https://www.scribbleshowdown.com/\n\n♥ The Team ♥\nAtrox: https://twitter.com/AtroxChobatsu\nDavidBaronArt: https://twitter.com/DavidBaronArt\nDee Helm: https://twitter.com/DeeRedHelm\nDenny: https://twitter.com/90PercentDenny\nDevon: https://www.youtube.com/channel/UCZaIIdSgN8aEUh7g_BgFobQ\nDuckdee: https://twitter.com/duckdeeArt\nJaystarz: https://www.youtube.com/xjaystarzx\nJRF\nMotiny: https://www.youtube.com/channel/UCHimPYk1csmmOSGKF4pKelg\nPivots: https://www.youtube.com/user/ThePivotsXXD\nTiffanySeng: https://twitter.com/tiffanyseng_art\n------------------------------------------------------------------------------------\nSUBSCRIBE for more animations!\nhttps://www.youtube.com/c/jaiden\n\nMERCH:\nhttps://jaidenanimations.com/\n\nTWITTER:\nhttps://twitter.com/JaidenAnimation\n\nINSTAGRAM:\nhttps://instagram.com/jaiden_animations\n\nIf you're an animator, artist, gamer, or entertainer, then join us at Channel Frederator Network: https://frdr.us/Jaiden\n\nWanna Send Fanart?\nYou can send it to me through Twitter or Instagram (links above)\n------------------------------------------------------------------------------------\nMusic: Amazing Island\n------------------------------------------------------------------------------------\n\n\n\n\nAnd this tells me you read the description, which means you respect what I have to say! Thank you :D i love my amazing island creations i wish creamer as real",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/IGf9jAank64/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/IGf9jAank64/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/IGf9jAank64/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/IGf9jAank64/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/IGf9jAank64/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Jaiden Animations',
      tags: [
        'jaiden',
        'animations',
        'jaidenanimation',
        'jaidenanimations',
        'amazing island',
        'jaidenanimation amazing island',
        'jaiden amazing island',
        'funny video',
        'tags',
        'hi',
      ],
      categoryId: '1',
      liveBroadcastContent: 'none',
      defaultLanguage: 'en',
      localized: {
        title: 'Amazing Island: The Game You Wish You Played',
        description:
          "shaped like friends\n\n\nAlpharad: https://www.youtube.com/user/alpharadd\nScribbleShowdown tickets: https://www.scribbleshowdown.com/\n\n♥ The Team ♥\nAtrox: https://twitter.com/AtroxChobatsu\nDavidBaronArt: https://twitter.com/DavidBaronArt\nDee Helm: https://twitter.com/DeeRedHelm\nDenny: https://twitter.com/90PercentDenny\nDevon: https://www.youtube.com/channel/UCZaIIdSgN8aEUh7g_BgFobQ\nDuckdee: https://twitter.com/duckdeeArt\nJaystarz: https://www.youtube.com/xjaystarzx\nJRF\nMotiny: https://www.youtube.com/channel/UCHimPYk1csmmOSGKF4pKelg\nPivots: https://www.youtube.com/user/ThePivotsXXD\nTiffanySeng: https://twitter.com/tiffanyseng_art\n------------------------------------------------------------------------------------\nSUBSCRIBE for more animations!\nhttps://www.youtube.com/c/jaiden\n\nMERCH:\nhttps://jaidenanimations.com/\n\nTWITTER:\nhttps://twitter.com/JaidenAnimation\n\nINSTAGRAM:\nhttps://instagram.com/jaiden_animations\n\nIf you're an animator, artist, gamer, or entertainer, then join us at Channel Frederator Network: https://frdr.us/Jaiden\n\nWanna Send Fanart?\nYou can send it to me through Twitter or Instagram (links above)\n------------------------------------------------------------------------------------\nMusic: Amazing Island\n------------------------------------------------------------------------------------\n\n\n\n\nAnd this tells me you read the description, which means you respect what I have to say! Thank you :D i love my amazing island creations i wish creamer as real",
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'JTBeMSbSpSg77uqOuNHT2Glo30A',
    id: 'RaAvUoOXTQY',
    snippet: {
      publishedAt: '2021-08-09T00:01:18Z',
      channelId: 'UCqQo7ewe87aYAe7ub5UqXMw',
      title:
        'LiAngelo Ball Hornets NBA DEBUT 🔥 16 PTS Full Highlights vs Trail Blazers | 2021 Summer League',
      description:
        'Portland Trail Blazers vs Charlotte Hornets - Full Game Highlights | August 8, 2021 NBA Summer League\n🚨SUBSCRIBE TO TTW: https://www.youtube.com/c/ThroughTheWireHoH 🚨\n\n📌 SHOP OUR MERCH: https://hoh.world\n\n#HouseofHighlights #NBA',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/RaAvUoOXTQY/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/RaAvUoOXTQY/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/RaAvUoOXTQY/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/RaAvUoOXTQY/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/RaAvUoOXTQY/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'House of Highlights',
      tags: [
        'liangelo ball',
        'liangelo ball charlotte hornets',
        'liangelo ball highlights',
        'liangelo ball hornets',
        'liangelo nba',
        'liangelo ball nba debut',
        'liangelo ball nba highlights',
      ],
      categoryId: '17',
      liveBroadcastContent: 'none',
      localized: {
        title:
          'LiAngelo Ball Hornets NBA DEBUT 🔥 16 PTS Full Highlights vs Trail Blazers | 2021 Summer League',
        description:
          'Portland Trail Blazers vs Charlotte Hornets - Full Game Highlights | August 8, 2021 NBA Summer League\n🚨SUBSCRIBE TO TTW: https://www.youtube.com/c/ThroughTheWireHoH 🚨\n\n📌 SHOP OUR MERCH: https://hoh.world\n\n#HouseofHighlights #NBA',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'dkWdtMLEdW2ZQlVbBeOjGDieLt0',
    id: 'OCU9k5iPXk8',
    snippet: {
      publishedAt: '2021-08-09T14:00:19Z',
      channelId: 'UCE_--R1P5-kfBzHTca0dsnw',
      title: 'Bobby Shmurda Goes Sneaker Shopping With Complex',
      description:
        "Bobby Shmurda goes Sneaker Shopping with Complex's Joe La Puma at Stadium Goods in New York City and talks about wanting Heelys growing up, his love of Air Jordans, and why he now wears designer sneakers.\n\n\nLooking for the best deal on a pair of sneakers? Download the Sole Collector app now!: https://solecollector.com/app  \n\nSubscribe to Complex on YouTube: https://www.youtube.com/c/Complex\n\nCheck out more of Complex here:\nhttps://www.twitch.tv/complex\nhttp://www.complex.com\nhttps://twitter.com/Complex\nhttps://www.facebook.com/complex\nhttp://instagram.com/complex\nhttps://plus.google.com/+complex/\n\nCOMPLEX is a community of creators and curators, armed with the Internet, committed to surfacing and sharing the voices and conversations that define our new America. Our videos exemplify convergence culture, exploring topics that include music, sneakers, style, sports, and pop culture through original shows and Complex News segments. Featuring your favorite celebrities, authoritative commentary, and a unique voice, our videos make culture pop.",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/OCU9k5iPXk8/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/OCU9k5iPXk8/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/OCU9k5iPXk8/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/OCU9k5iPXk8/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/OCU9k5iPXk8/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Complex',
      tags: [
        'sneakerhead',
        'complex',
        'complex originals',
        'sneakers',
        'news',
        'entertainment',
        'current affairs',
        'culture',
        'complex tv',
        'complex media',
        'complex networks',
        'bobby scmurda',
        'bobby shmurda new song',
        'bobby shmurda',
        'about a week ago',
        'bobby schmurda nyc',
        'bobby schmurda rolling loud',
        'bobby schmurda sneakers',
        'heelys',
      ],
      categoryId: '24',
      liveBroadcastContent: 'none',
      localized: {
        title: 'Bobby Shmurda Goes Sneaker Shopping With Complex',
        description:
          "Bobby Shmurda goes Sneaker Shopping with Complex's Joe La Puma at Stadium Goods in New York City and talks about wanting Heelys growing up, his love of Air Jordans, and why he now wears designer sneakers.\n\n\nLooking for the best deal on a pair of sneakers? Download the Sole Collector app now!: https://solecollector.com/app  \n\nSubscribe to Complex on YouTube: https://www.youtube.com/c/Complex\n\nCheck out more of Complex here:\nhttps://www.twitch.tv/complex\nhttp://www.complex.com\nhttps://twitter.com/Complex\nhttps://www.facebook.com/complex\nhttp://instagram.com/complex\nhttps://plus.google.com/+complex/\n\nCOMPLEX is a community of creators and curators, armed with the Internet, committed to surfacing and sharing the voices and conversations that define our new America. Our videos exemplify convergence culture, exploring topics that include music, sneakers, style, sports, and pop culture through original shows and Complex News segments. Featuring your favorite celebrities, authoritative commentary, and a unique voice, our videos make culture pop.",
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'Xl8stnfqPJk_sNXBV8T1dRnqrL4',
    id: '9LMr5XTgeyI',
    snippet: {
      publishedAt: '2021-08-09T11:45:13Z',
      channelId: 'UC2C_jShtL725hvbm1arSV9w',
      title: '💖 The Tale of Tiffany 💖',
      description:
        '‣ Thank you, Bonnie Bees, for making this video possible: https://www.patreon.com/cgpgrey\n\n‣ Discuss this video: https://www.reddit.com/r/cgpgrey\n\n## Related Links\n\nSHARKS! https://www.youtube.com/watch?v=_8xhdL8BPvU\n\nhttps://www.tylervigen.com/spurious-correlations\n\n## Special Thanks\n\nDr. Richard Coates, Professor Emeritus of Onomastics, Bristol Centre for Linguistics, University of the West of England\n\nDr. Gregory Clark, Distinguished Professor of Economics, University of California, Davis\n\n## Bonnie Bees\n\nBen Delo, Bob Kunz, Bobby, Nevin Spoljaric, Donal Botkin, BN-12, Andrew Bereza, Rebecca Wortham, Richard Jenkins, Marco Arment, Phil Gardner, Martin, Steven Grimm, Colin Millions, emptymachine, George Lin, Jason Lewandowski, Saki Comandao, David Tyler, iulus, Jordan Earls, Nick Fish, Nick Gibson, Tyler Bryant, Xueqi, Oliver Steele, Kermit Norlund, rictic, Alex Simonides, Tim Stumbaugh, Nicholas Welna, Christopher Mutchler, Derek Bonner, Mikko, Orbit_Junkie, Tómas Árni Jónasson, Bear, chrysilis, David Palomares, Drago175, Emil, Esteban Santana Santana, Freddi Hørlyck, John Rogers, Peter Lomax, Rhys Parry, ShiroiYami, Tristan Watts-Willis, Veronica Peshterianu, Dag Viggo Lokøen, John Lee, Maxime Zielony, Elizabeth Keathley, Birdstryke, AUFFRAY Clement\n\n## Music\n\nDavid Rees: http://www.davidreesmusic.com',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/9LMr5XTgeyI/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/9LMr5XTgeyI/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/9LMr5XTgeyI/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/9LMr5XTgeyI/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/9LMr5XTgeyI/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'CGP Grey',
      tags: ['cgpgrey', 'education', 'hello internet'],
      categoryId: '27',
      liveBroadcastContent: 'none',
      defaultLanguage: 'en',
      localized: {
        title: '💖 The Tale of Tiffany 💖',
        description:
          '‣ Thank you, Bonnie Bees, for making this video possible: https://www.patreon.com/cgpgrey\n\n‣ Discuss this video: https://www.reddit.com/r/cgpgrey\n\n## Related Links\n\nSHARKS! https://www.youtube.com/watch?v=_8xhdL8BPvU\n\nhttps://www.tylervigen.com/spurious-correlations\n\n## Special Thanks\n\nDr. Richard Coates, Professor Emeritus of Onomastics, Bristol Centre for Linguistics, University of the West of England\n\nDr. Gregory Clark, Distinguished Professor of Economics, University of California, Davis\n\n## Bonnie Bees\n\nBen Delo, Bob Kunz, Bobby, Nevin Spoljaric, Donal Botkin, BN-12, Andrew Bereza, Rebecca Wortham, Richard Jenkins, Marco Arment, Phil Gardner, Martin, Steven Grimm, Colin Millions, emptymachine, George Lin, Jason Lewandowski, Saki Comandao, David Tyler, iulus, Jordan Earls, Nick Fish, Nick Gibson, Tyler Bryant, Xueqi, Oliver Steele, Kermit Norlund, rictic, Alex Simonides, Tim Stumbaugh, Nicholas Welna, Christopher Mutchler, Derek Bonner, Mikko, Orbit_Junkie, Tómas Árni Jónasson, Bear, chrysilis, David Palomares, Drago175, Emil, Esteban Santana Santana, Freddi Hørlyck, John Rogers, Peter Lomax, Rhys Parry, ShiroiYami, Tristan Watts-Willis, Veronica Peshterianu, Dag Viggo Lokøen, John Lee, Maxime Zielony, Elizabeth Keathley, Birdstryke, AUFFRAY Clement\n\n## Music\n\nDavid Rees: http://www.davidreesmusic.com',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'zamydURxGo8BDQPtQhmzATk2JRM',
    id: 'Cdsf75RB3LM',
    snippet: {
      publishedAt: '2021-08-08T16:00:03Z',
      channelId: 'UCL6JmiMXKoXS6bpP1D3bk8g',
      title: '$800 Off-Road Tires vs. $1500 Off-Road Tires',
      description:
        "Thanks to Ebay Motors for sponsoring today’s video! CLICK here https://ebayvehicle.com/app/Donut to search through thousands of cars and parts & list those project cars and spare parts sitting around!\n\nWe bought two identical Toyota Tacomas, and we’ve been modifying them to be fun, daily drivers that you can take literally anywhere, except the ocean. \n\nOne Taco gets expensive parts, and one gets cheap parts. Then we test them, to see which components are worth spending your hard-earned money on.\n\nHi Truck is getting a set of Nitto Ridge Grappler All-Terrains…\nat $342 per tire!\nAnd Low Truck is getting some enda Klever All-Terrainss which are less than half the price at $147 per tire\n.\n\nNew to the Channel? \n►Watch this: https://www.youtube.com/playlist?list=PLFl907chpCa42gkh1oJxuJBN0cZ4YT1HT\n\nWe upload almost every day, subscribe so you don't miss out!\n►Subscribe here: http://bit.ly/1JQ3qvO\n\nClick here for more info on joining the Donut Underground!\n►https://www.youtube.com/channel/UCL6JmiMXKoXS6bpP1D3bk8g/join\n\nShop Donut Merch: \n►http://www.donut.media/\n\nDonut Media is at the center of digital media for the next generation of automotive and motorsports enthusiasts. We are drivers, drifters, and car enthusiasts who love to tell stories.",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/Cdsf75RB3LM/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/Cdsf75RB3LM/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/Cdsf75RB3LM/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/Cdsf75RB3LM/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/Cdsf75RB3LM/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Donut Media',
      tags: [
        'high low',
        'hilow',
        'cheap expensive',
        'doughnut media',
        'hilo',
        'hi lo',
        'tires',
        'tyres',
        'wheels and tires',
        'offroad',
        'off-roading',
        'overland',
        'camping truck',
        'donut media',
        'james pumphrey',
        'james humphrey',
        'zach jobe',
        'nolan sykes',
        'aaron parker',
      ],
      categoryId: '2',
      liveBroadcastContent: 'none',
      defaultLanguage: 'en',
      localized: {
        title: '$800 Off-Road Tires vs. $1500 Off-Road Tires',
        description:
          "Thanks to Ebay Motors for sponsoring today’s video! CLICK here https://ebayvehicle.com/app/Donut to search through thousands of cars and parts & list those project cars and spare parts sitting around!\n\nWe bought two identical Toyota Tacomas, and we’ve been modifying them to be fun, daily drivers that you can take literally anywhere, except the ocean. \n\nOne Taco gets expensive parts, and one gets cheap parts. Then we test them, to see which components are worth spending your hard-earned money on.\n\nHi Truck is getting a set of Nitto Ridge Grappler All-Terrains…\nat $342 per tire!\nAnd Low Truck is getting some enda Klever All-Terrainss which are less than half the price at $147 per tire\n.\n\nNew to the Channel? \n►Watch this: https://www.youtube.com/playlist?list=PLFl907chpCa42gkh1oJxuJBN0cZ4YT1HT\n\nWe upload almost every day, subscribe so you don't miss out!\n►Subscribe here: http://bit.ly/1JQ3qvO\n\nClick here for more info on joining the Donut Underground!\n►https://www.youtube.com/channel/UCL6JmiMXKoXS6bpP1D3bk8g/join\n\nShop Donut Merch: \n►http://www.donut.media/\n\nDonut Media is at the center of digital media for the next generation of automotive and motorsports enthusiasts. We are drivers, drifters, and car enthusiasts who love to tell stories.",
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'Lr2vuUaCP7J8VYFpYHSL-fZS4Gs',
    id: 'NwSKJJurBKc',
    snippet: {
      publishedAt: '2021-08-07T18:00:13Z',
      channelId: 'UCCneh1EgWLS8atIUujHr4Og',
      title: 'Cool Tip I Learned from Reddit',
      description:
        "SUBSCRIBE for the BEST daily Warzone videos! \nSend in YOUR clips HERE ⏩ https://forms.gle/pG1RqMiqLSnUCKj47\n\nMassive thanks to for letting us feature this clip!\n\nWelcome to Patchy's Top Plays! Every day, we post the best, funniest and top Warzone moments and highlights. If you love Call of Duty Warzone and want to keep up with what the best Warzone players are doing to get their wins, then be sure to subscribe! By keeping up with our latest videos, you'll find out the best Warzone tricks and tips, and also be able to see what the best Warzone loadouts and best Warzone guns are between each patch.\n\n#shorts",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/NwSKJJurBKc/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/NwSKJJurBKc/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/NwSKJJurBKc/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/NwSKJJurBKc/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/NwSKJJurBKc/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "Patchy's Top Plays",
      tags: [
        'warzone',
        'call of duty best',
        'call of duty funny',
        'funny moments',
        'epic moments',
        'call of duty wtf moments',
        'cod funny',
        'cod',
        'top call of duty plays',
        'call of duty warzone',
        'warzone highlights',
        'warzone best moments',
        'warzone funny moments',
        'warzone best plays',
        'cod warzone',
        'top warzone plays',
        'warzone best',
        'warzone best gun',
        'warzone funny',
        "patchy's top plays",
        'best warzone players',
        'best warzone player',
        'best warzone plays',
        'top warzone moments',
        'top warzone clips',
        'call of duty',
        '#shorts',
      ],
      categoryId: '20',
      liveBroadcastContent: 'none',
      localized: {
        title: 'Cool Tip I Learned from Reddit',
        description:
          "SUBSCRIBE for the BEST daily Warzone videos! \nSend in YOUR clips HERE ⏩ https://forms.gle/pG1RqMiqLSnUCKj47\n\nMassive thanks to for letting us feature this clip!\n\nWelcome to Patchy's Top Plays! Every day, we post the best, funniest and top Warzone moments and highlights. If you love Call of Duty Warzone and want to keep up with what the best Warzone players are doing to get their wins, then be sure to subscribe! By keeping up with our latest videos, you'll find out the best Warzone tricks and tips, and also be able to see what the best Warzone loadouts and best Warzone guns are between each patch.\n\n#shorts",
      },
    },
  },
  {
    kind: 'youtube#video',
    etag: 'IE7WtlP5x4dhzsuhhJwbSJJ0dPU',
    id: 'EeCX8Y0a278',
    snippet: {
      publishedAt: '2021-08-08T04:00:00Z',
      channelId: 'UCWOA1ZGywLbqmigxE4Qlvuw',
      title:
        'JoJo’s Bizarre Adventure STONE OCEAN | Official Trailer | Netflix',
      description:
        "2011, United States, Florida —\nWhen Jolyne Cujoh and her boyfriend get in an accident while out on a drive, she is framed for the crime and sentenced to 15 years in prison.\n\nWill she ever be free from this prison — this stone ocean?\n\nThe final battle in the century-spanning, intertwining fate of the Joestar family and DIO begins!\n\nJoJo’s Bizarre Adventure STONE OCEAN,\nPremiering worldwide from December 2021, only on Netflix!\n\nSUBSCRIBE: http://bit.ly/29qBUt7\n\nAbout Netflix:\nNetflix is the world's leading streaming entertainment service with over 209 million paid memberships in over 190 countries enjoying TV series, documentaries and feature films across a wide variety of genres and languages. Members can watch as much as they want, anytime, anywhere, on any internet-connected screen. Members can play, pause and resume watching, all without commercials or commitments.\n\nJoJo’s Bizarre Adventure STONE OCEAN | Official Trailer | Netflix\nhttps://youtube.com/Netflix",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/EeCX8Y0a278/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/EeCX8Y0a278/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/EeCX8Y0a278/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/EeCX8Y0a278/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/EeCX8Y0a278/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Netflix',
      tags: ['Anime', "JoJo's Bizarre Adventure", 'Netflix', 'Stone Ocean'],
      categoryId: '24',
      liveBroadcastContent: 'none',
      localized: {
        title:
          'JoJo’s Bizarre Adventure STONE OCEAN | Official Trailer | Netflix',
        description:
          "2011, United States, Florida —\nWhen Jolyne Cujoh and her boyfriend get in an accident while out on a drive, she is framed for the crime and sentenced to 15 years in prison.\n\nWill she ever be free from this prison — this stone ocean?\n\nThe final battle in the century-spanning, intertwining fate of the Joestar family and DIO begins!\n\nJoJo’s Bizarre Adventure STONE OCEAN,\nPremiering worldwide from December 2021, only on Netflix!\n\nSUBSCRIBE: http://bit.ly/29qBUt7\n\nAbout Netflix:\nNetflix is the world's leading streaming entertainment service with over 209 million paid memberships in over 190 countries enjoying TV series, documentaries and feature films across a wide variety of genres and languages. Members can watch as much as they want, anytime, anywhere, on any internet-connected screen. Members can play, pause and resume watching, all without commercials or commitments.\n\nJoJo’s Bizarre Adventure STONE OCEAN | Official Trailer | Netflix\nhttps://youtube.com/Netflix",
      },
      defaultAudioLanguage: 'en-US',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'vHnm-ShWHTDSo1wIgEuuudxrA_E',
    id: 'y8vtq3B8wkY',
    snippet: {
      publishedAt: '2021-08-09T02:19:53Z',
      channelId: 'UC_ovJB6xS99RQGIq7ik5T_A',
      title: 'WE DID THIS AT MY 1ST CONCERT! **MUST WATCH**',
      description:
        'CHECK OUT MY PODCAST CHANNEL!\nhttps://www.youtube.com/channel/UCgJ8g5IpImRPgXWgawMpajw\n\nMERCH AVAILABLE AT https://bennysoliven.co\n\nSUBSCRIBE \n@Benny Soliven \n@AlondraDessy \n@Jivenchy Filmz\n\nFOLLOW ME ON INSTAGRAM\nhttps://www.instagram.com/bennysoliven/?hl=en\nFOLLOW ME ON TWITTER\nhttps://twitter.com/BennySoliven\nFOLLOW ME ON SNAPCHAT\n@benstuh\n\nFor Business Inquiries: contact@tablerockmanagement.com',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/y8vtq3B8wkY/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/y8vtq3B8wkY/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/y8vtq3B8wkY/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/y8vtq3B8wkY/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/y8vtq3B8wkY/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Benny Soliven',
      categoryId: '22',
      liveBroadcastContent: 'none',
      localized: {
        title: 'WE DID THIS AT MY 1ST CONCERT! **MUST WATCH**',
        description:
          'CHECK OUT MY PODCAST CHANNEL!\nhttps://www.youtube.com/channel/UCgJ8g5IpImRPgXWgawMpajw\n\nMERCH AVAILABLE AT https://bennysoliven.co\n\nSUBSCRIBE \n@Benny Soliven \n@AlondraDessy \n@Jivenchy Filmz\n\nFOLLOW ME ON INSTAGRAM\nhttps://www.instagram.com/bennysoliven/?hl=en\nFOLLOW ME ON TWITTER\nhttps://twitter.com/BennySoliven\nFOLLOW ME ON SNAPCHAT\n@benstuh\n\nFor Business Inquiries: contact@tablerockmanagement.com',
      },
    },
  },
  {
    kind: 'youtube#video',
    etag: 'Nnv5vioCzjbZ6DSQ2exy1Xt0T7c',
    id: 'lQ3o6CzP-2Q',
    snippet: {
      publishedAt: '2021-08-08T17:50:39Z',
      channelId: 'UCGTKwjs1ctvgwCRa67RNO-Q',
      title: 'The Largest And Most Stuck Excavator I’ve Ever Recovered',
      description:
        'Get an insane 70% off the kove headphones for a limited time here: http://koveaudio.com/hs70\nCode HS70 (any headphones)\n\nMore details about my Sany Equipment here bit.ly/HeavySany\n\n\nYou can win one of my personal vehicles by subscribing to both of my channels right now!\nhttps://www.youtube.com/c/HeavyDSparks\nhttps://www.youtube.com/channel/UCdhpSU6k5mRE8okyK3ZdmeQ\n\nAdvertising and partnership inquiries email info@heavydsparks.com\n\nFollow Me on Insta: https://www.instagram.com/heavydsparks/?hl=en',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/lQ3o6CzP-2Q/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/lQ3o6CzP-2Q/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/lQ3o6CzP-2Q/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/lQ3o6CzP-2Q/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/lQ3o6CzP-2Q/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'HeavyDSparks',
      tags: [
        'Recovery',
        'Diesel',
        'Diesel brothers',
        'Heavy equipment',
        'Cat',
        'Caterpillar',
        'Whistlindiesel',
        'Cleetus McFarland',
        'Demolition ranch',
        'Letsdig18',
        'Matt’s Offroad',
        'Yankum',
        'Mud',
        'Adventure',
        'For you',
        'Heavydsparks',
        'Sparks motors',
        'Freedom bus',
        'Dirt',
        'Dirt work',
        'Tractor',
        'Machine',
        'Dave sparks',
        'Diesel Dave',
        'Dieseldave',
      ],
      categoryId: '22',
      liveBroadcastContent: 'none',
      localized: {
        title: 'The Largest And Most Stuck Excavator I’ve Ever Recovered',
        description:
          'Get an insane 70% off the kove headphones for a limited time here: http://koveaudio.com/hs70\nCode HS70 (any headphones)\n\nMore details about my Sany Equipment here bit.ly/HeavySany\n\n\nYou can win one of my personal vehicles by subscribing to both of my channels right now!\nhttps://www.youtube.com/c/HeavyDSparks\nhttps://www.youtube.com/channel/UCdhpSU6k5mRE8okyK3ZdmeQ\n\nAdvertising and partnership inquiries email info@heavydsparks.com\n\nFollow Me on Insta: https://www.instagram.com/heavydsparks/?hl=en',
      },
    },
  },
  {
    kind: 'youtube#video',
    etag: '6BtM9iZCFIfnZ5LFgBTA5BeQmSY',
    id: 'ifqqp7kH_tQ',
    snippet: {
      publishedAt: '2021-08-07T23:10:46Z',
      channelId: 'UC4G10tk3AHFuyMIuD3rHOBA',
      title: 'HOOD OLYMPICS 3',
      description:
        "It's the season of the Olympics so you know what that means! But instead of Tokyo we're taking it to the hood 😂😂 who's gonna take the gold??\n\n\n~RDC Social Media ~\n\n@RDCWorld1\nMark Phillips - @SupremeDreams_1\nAffiong Harris - @CleanUniform\nDesmond Johnson - @l0v3andPeac3\nLeland Manigo - @23_Is_Leland\nDylan Patel - @DylanPatel4_\nBenjamin Skinner - @Ive_Ben_Jammin\nJohnathan Newton - @PlayThatJohn\n\nSong in the credits:\nhttps://www.youtube.com/watch?v=LnJqPpFMJYI\n\nMERCH\nhttps://rdcworld1.com/collections/all\n\nGAMING CHANNEL\nhttps://www.youtube.com/channel/UCW0uwJNcMTiOFXXgyS2no4g\n\nTWITCH CHANNEL\nhttps://www.twitch.tv/rdcgaming\n\nDREAM CON INFO!\nhttps://www.dreamconvention.com\n\nDISCORD\ndiscord.gg/rdcworld1\n\nSOUNDCLOUD\nhttps://soundcloud.com/rdcworld",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/ifqqp7kH_tQ/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/ifqqp7kH_tQ/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/ifqqp7kH_tQ/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/ifqqp7kH_tQ/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/ifqqp7kH_tQ/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'RDCworld1',
      categoryId: '23',
      liveBroadcastContent: 'none',
      localized: {
        title: 'HOOD OLYMPICS 3',
        description:
          "It's the season of the Olympics so you know what that means! But instead of Tokyo we're taking it to the hood 😂😂 who's gonna take the gold??\n\n\n~RDC Social Media ~\n\n@RDCWorld1\nMark Phillips - @SupremeDreams_1\nAffiong Harris - @CleanUniform\nDesmond Johnson - @l0v3andPeac3\nLeland Manigo - @23_Is_Leland\nDylan Patel - @DylanPatel4_\nBenjamin Skinner - @Ive_Ben_Jammin\nJohnathan Newton - @PlayThatJohn\n\nSong in the credits:\nhttps://www.youtube.com/watch?v=LnJqPpFMJYI\n\nMERCH\nhttps://rdcworld1.com/collections/all\n\nGAMING CHANNEL\nhttps://www.youtube.com/channel/UCW0uwJNcMTiOFXXgyS2no4g\n\nTWITCH CHANNEL\nhttps://www.twitch.tv/rdcgaming\n\nDREAM CON INFO!\nhttps://www.dreamconvention.com\n\nDISCORD\ndiscord.gg/rdcworld1\n\nSOUNDCLOUD\nhttps://soundcloud.com/rdcworld",
      },
    },
  },
  {
    kind: 'youtube#video',
    etag: 'r3yllgNC_hQOkYWY7oA9M15Qjdc',
    id: 'jXpg3aTpeXA',
    snippet: {
      publishedAt: '2021-08-09T17:00:23Z',
      channelId: 'UCk9xNdmgY8im4RDCops9YYw',
      title: 'GTA 5 Roleplay - SURVIVING TINY $1,000,000 BOUNTY | RedlineRP',
      description:
        'That was crazy...\nToday I became tiny again, but this time I set a $1Million dollar bounty on myself and needed to survive it. A lot of people tried to claim the money and I had a ton of crazy escapes. The cops ended up coming too and it was pretty insane. There are a lot of funny moments in this GTA 5 episode, enjoy! \n\nMERCH - https://treyten.merchforall.com/\n\nINSTAGRAM - https://www.instagram.com/treyt3n​​​​​​​\n\nFollow My Social Media To Stay Connected!\nInstagram - https://www.instagram.com/treyt3n​​​​​​​\nDiscord - https://discord.gg/dUXsTEC​​​​​​​\nSnapchat - https://www.snapchat.com/add/treyteni...\n\nSubscribe for more!\nIf u read this far down in the desc I love u!',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/jXpg3aTpeXA/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/jXpg3aTpeXA/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/jXpg3aTpeXA/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/jXpg3aTpeXA/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/jXpg3aTpeXA/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Treyten',
      tags: [
        'GTA 5',
        'bounty hunters',
        'gta 5 roleplay',
        'surviving bounty',
        'tiny hitmen',
        'funny moments',
        'grand theft auto',
        'GTA ONLINE',
        'gta 5 mods',
        'roleplay',
        'Treyten',
        'RedlineRP',
      ],
      categoryId: '20',
      liveBroadcastContent: 'none',
      localized: {
        title: 'GTA 5 Roleplay - SURVIVING TINY $1,000,000 BOUNTY | RedlineRP',
        description:
          'That was crazy...\nToday I became tiny again, but this time I set a $1Million dollar bounty on myself and needed to survive it. A lot of people tried to claim the money and I had a ton of crazy escapes. The cops ended up coming too and it was pretty insane. There are a lot of funny moments in this GTA 5 episode, enjoy! \n\nMERCH - https://treyten.merchforall.com/\n\nINSTAGRAM - https://www.instagram.com/treyt3n​​​​​​​\n\nFollow My Social Media To Stay Connected!\nInstagram - https://www.instagram.com/treyt3n​​​​​​​\nDiscord - https://discord.gg/dUXsTEC​​​​​​​\nSnapchat - https://www.snapchat.com/add/treyteni...\n\nSubscribe for more!\nIf u read this far down in the desc I love u!',
      },
      defaultAudioLanguage: 'en-US',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'LX8YaSvLNOPwSHbB0BzzKEtuR-w',
    id: '-vPDzTEyryU',
    snippet: {
      publishedAt: '2021-08-08T23:40:52Z',
      channelId: 'UC9tXyGZiEft9J4ZiI8dHb3Q',
      title: 'Minecraft, But There Are Custom Biomes...',
      description:
        'Minecraft, But There Are Custom Biomes...\n\nThanks for Watching! :D I appreciate all feedback and support :L!\n\nEdited By @ExtremeBlitz \n\nPATREON → https://www.patreon.com/TapLHarV\nBecoming a patron will allow you to download all my Minecraft mods and plugins I use in my Minecraft But videos series and by doing so you support my developers that help me make these videos in the first place!\n\nTWITCH STREAMS → https://twitch.tv/tapl\nTAPL MERCH → https://tapl.store\n\nTikTok → https://www.tiktok.com/@taplharv\nTwitter → https://twitter.com/TapLHarV \nDiscord Server → https://discord.gg/TapL\nInstagram → https://instagram.com/taplharv\nSnapchat → itstapl\n\nThis is a Minecraft 1.16 challenge where I am beating Minecraft as fast as possible (Minecraft speedrun) to beat the game! However, the twist is that there are custom biomes. This is a "Minecraft, But" challenge, not beating minecraft but my friend tries to stop me AKA Minecraft Speedrunner VS Hunter AKA Minecraft Manhunt, Minecraft UHC, Minecraft PvP, nor Minecraft SMP. :L\n\n#MinecraftBut #MinecraftChallenge #Minecraft #TapL',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/-vPDzTEyryU/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/-vPDzTEyryU/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/-vPDzTEyryU/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/-vPDzTEyryU/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/-vPDzTEyryU/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'TapL',
      tags: [
        'Minecraft',
        'Competitive Minecraft',
        'Minecraft PvP',
        'TapL',
        'UHC',
        'Ultra Hardcore',
        'Crazy UHC',
        'Insane Minecraft',
        'Minecraft Minigames',
        'Tapple',
        'Tapple Events',
        'Tapple Minecraft',
        'Tapple Server',
        'Tapple UHC',
        'TapL UHC',
        'TapL Challenge',
        'Challenge',
        'Tapple Challenge',
        'Minecraft But',
        'Minecraft UHC But',
        'MinecraftBut',
        'Minecraft Challenge',
        'Minecraft Challenges',
        'Minecraft Hardcore',
        'Beating Minecraft',
        'Minecraft OP',
        'OP Minecraft',
        'Blessed Minecraft',
        'Cursed Minecraft',
        'Minecraft Scenario',
        'Minecraft UHC',
      ],
      categoryId: '20',
      liveBroadcastContent: 'none',
      localized: {
        title: 'Minecraft, But There Are Custom Biomes...',
        description:
          'Minecraft, But There Are Custom Biomes...\n\nThanks for Watching! :D I appreciate all feedback and support :L!\n\nEdited By @ExtremeBlitz \n\nPATREON → https://www.patreon.com/TapLHarV\nBecoming a patron will allow you to download all my Minecraft mods and plugins I use in my Minecraft But videos series and by doing so you support my developers that help me make these videos in the first place!\n\nTWITCH STREAMS → https://twitch.tv/tapl\nTAPL MERCH → https://tapl.store\n\nTikTok → https://www.tiktok.com/@taplharv\nTwitter → https://twitter.com/TapLHarV \nDiscord Server → https://discord.gg/TapL\nInstagram → https://instagram.com/taplharv\nSnapchat → itstapl\n\nThis is a Minecraft 1.16 challenge where I am beating Minecraft as fast as possible (Minecraft speedrun) to beat the game! However, the twist is that there are custom biomes. This is a "Minecraft, But" challenge, not beating minecraft but my friend tries to stop me AKA Minecraft Speedrunner VS Hunter AKA Minecraft Manhunt, Minecraft UHC, Minecraft PvP, nor Minecraft SMP. :L\n\n#MinecraftBut #MinecraftChallenge #Minecraft #TapL',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: '_h1Rb-PAnU6aBr1-YowC5HBKV6s',
    id: 'R9Y-wxDTKZk',
    snippet: {
      publishedAt: '2021-08-08T22:31:18Z',
      channelId: 'UCWOJOAu-sSng-QQ3dnEBnRg',
      title:
        "Matt vs Boyfriend Boxing Fight Part 2 (Friday Night Funkin' Animation)",
      description:
        'The Part 2 to the Matt VS Boyfriend Boxing Fight Animation is here! But this time, Matt has had enough of Boyfriend.\n\nFan-made Matt Boxing Mod: https://gamebanana.com/mods/308568\n\n(Original Mod) Wii Funkin (vs Matt) Mod: https://gamebanana.com/mods/44511\n\nCredits to:\n\nCritVA (Voice of Matt): https://www.youtube.com/c/critva\n\n"Wii Funkin vs Matt Mod" for FNF X Matt concept\nThe fan-made WiiK 3 Mod for Matt\'s boxing outfit concept\n"Friday Night Funkin" for the "Friday Night Funkin" concept\n"Nintendo Wii Sports" for the "Wii Sports" and "Matt" concept\n\nSongs used in order:\n"Sporting": https://www.youtube.com/watch?v=Rssf-PXdsiE\n"Sporting Instrumental - Slowed Down": https://youtu.be/TawcN6R2UPA  (I made the pitch higher in my video)\n"Boxing Match Insrumental": https://www.youtube.com/watch?v=WcAoU80fN08\n\n0:00 Intro\n0:10 The Mod!\n0:19 Part 3\n0:33 The Fight\n2:56 Plot?!\n5:52 Credits\n6:03 More On Part 3\n6:23 Sprite Sheets\n6:46 The Stands\n7:21 End\n\n#FridayNightFunkinanimation #FNFMattMod \n#WiiK2\n\nAnimation Software: Adobe Animate CC\nEditing Software: Filmora9 / Adobe Premier Pro\nDrawing tablet: Ugee M708 graphics tab',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/R9Y-wxDTKZk/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/R9Y-wxDTKZk/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/R9Y-wxDTKZk/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/R9Y-wxDTKZk/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/R9Y-wxDTKZk/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: "Chino's Animated",
      tags: [
        "Chino's Animated",
        'Friday Night Funkin',
        'FNF',
        'Vs Matt',
        'Wii Funkin',
        'Matt Boxing',
        'Animation',
        'Fight',
      ],
      categoryId: '1',
      liveBroadcastContent: 'none',
      defaultLanguage: 'en-GB',
      localized: {
        title:
          "Matt vs Boyfriend Boxing Fight Part 2 (Friday Night Funkin' Animation)",
        description:
          'The Part 2 to the Matt VS Boyfriend Boxing Fight Animation is here! But this time, Matt has had enough of Boyfriend.\n\nFan-made Matt Boxing Mod: https://gamebanana.com/mods/308568\n\n(Original Mod) Wii Funkin (vs Matt) Mod: https://gamebanana.com/mods/44511\n\nCredits to:\n\nCritVA (Voice of Matt): https://www.youtube.com/c/critva\n\n"Wii Funkin vs Matt Mod" for FNF X Matt concept\nThe fan-made WiiK 3 Mod for Matt\'s boxing outfit concept\n"Friday Night Funkin" for the "Friday Night Funkin" concept\n"Nintendo Wii Sports" for the "Wii Sports" and "Matt" concept\n\nSongs used in order:\n"Sporting": https://www.youtube.com/watch?v=Rssf-PXdsiE\n"Sporting Instrumental - Slowed Down": https://youtu.be/TawcN6R2UPA  (I made the pitch higher in my video)\n"Boxing Match Insrumental": https://www.youtube.com/watch?v=WcAoU80fN08\n\n0:00 Intro\n0:10 The Mod!\n0:19 Part 3\n0:33 The Fight\n2:56 Plot?!\n5:52 Credits\n6:03 More On Part 3\n6:23 Sprite Sheets\n6:46 The Stands\n7:21 End\n\n#FridayNightFunkinanimation #FNFMattMod \n#WiiK2\n\nAnimation Software: Adobe Animate CC\nEditing Software: Filmora9 / Adobe Premier Pro\nDrawing tablet: Ugee M708 graphics tab',
      },
      defaultAudioLanguage: 'en-GB',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'GgQGT2_qma8sUZqT79rDMvKIkFY',
    id: '3VZzO2UENsQ',
    snippet: {
      publishedAt: '2021-08-07T21:59:22Z',
      channelId: 'UC9HlWVtENbiMQzVRmnbJxtw',
      title: 'Meek Mill - War Stories',
      description:
        'Meek Mill -\r War Stories\n\r\nSubscribe for more official content from Meek Mill:\r\nhttps://MeekMill.lnk.to/subscribe\r\n\r\nFollow Meek Mill\r\nhttp://meekMill.com\r\nhttp://twitter.com/MeekMill\r\nhttp://facebook.com/MeekMill\r\nhttp://instagram.com/MeekMill\r\nhttps://soundcloud.com/meek-mill-dc\r\n\r\nThe official YouTube channel of Atlantic Records artist Meek Mill. Subscribe for the latest music videos, performances, and more.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/3VZzO2UENsQ/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/3VZzO2UENsQ/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/3VZzO2UENsQ/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/3VZzO2UENsQ/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/3VZzO2UENsQ/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Meek Mill',
      tags: [
        'meek mill',
        'meek',
        'mill',
        'hip hop',
        'rap',
        'atlantic',
        'atlantic records',
        'wins & losses',
        'dreams worth more than money',
        'stay woke',
        'dangerous',
        'champions',
        'championship',
        'championship rings',
        'rings',
        'Intro',
        'trauma',
        'uptwon vibes',
        'on me',
        'cardi b',
        'whats free',
        'Respect the game',
        'splash warning',
        'going bad',
        'drake',
        'almost slipped',
        'tic tac toe',
        '24/7',
        'pay you back',
        '21 savage',
        '100 summers',
        'wit the shits',
        'stuck in my ways',
        'cold hearted ii',
      ],
      categoryId: '10',
      liveBroadcastContent: 'none',
      localized: {
        title: 'Meek Mill - War Stories',
        description:
          'Meek Mill -\r War Stories\n\r\nSubscribe for more official content from Meek Mill:\r\nhttps://MeekMill.lnk.to/subscribe\r\n\r\nFollow Meek Mill\r\nhttp://meekMill.com\r\nhttp://twitter.com/MeekMill\r\nhttp://facebook.com/MeekMill\r\nhttp://instagram.com/MeekMill\r\nhttps://soundcloud.com/meek-mill-dc\r\n\r\nThe official YouTube channel of Atlantic Records artist Meek Mill. Subscribe for the latest music videos, performances, and more.',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: '6G7pXiGm65FZmh1JXjNN3j0nyqU',
    id: '9tuqIkyyljU',
    snippet: {
      publishedAt: '2021-08-09T16:37:46Z',
      channelId: 'UC2TT4PdhvEBgdAmrGv-2QuA',
      title: 'Dead By Daylight Parody 14 - Resident Evil (Animated)',
      description:
        "The Hookers plan their next move.\n\n►UPCOMING VIDS: https://bit.ly/2Qrdxky\n►JOIN SAMINATION: https://goo.gl/Xb18UC\n►DISCORD: https://discord.gg/un2gJFd\n►MERCH: https://teespring.com/stores/samination\n►TWITTER: http://www.twitter.com/saminating\n►INSTAGRAM: https://instagram.com/instasamination\n►PATREON: http://www.patreon.com/samination\n►SOUNDS/RINGTONES: https://samination.bandcamp.com\n\nSEND REAL MAIL TO:\nSam T Nelson\n9445 Coors Blvd NW @159\nAlbuquerque, NM 87114\n\n#samination #animation #parody\n\n0:00 Resident Leon\n1:09 Oh-No Mither\n1:57 Happy Anniversary\n2:46 Mean Plague\n3:31 Killer's Meeting\n4:53 Frank Mori's himself",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/9tuqIkyyljU/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/9tuqIkyyljU/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/9tuqIkyyljU/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/9tuqIkyyljU/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/9tuqIkyyljU/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Samination',
      tags: [
        'animation',
        'comedy',
        'parody',
        'dead by daylight',
        'animation meme',
        'comedy scenes',
        'resident evil',
        'dead by daylight new killer',
        'dead by daylight parody',
        'dead by daylight animation',
        'leon kennedy',
        'dead by daylight parody animation',
        'dead by daylight resident evil',
        'dead by daylight nemesis',
        'jill valentine',
        'nea',
        'what now',
        'ash williams',
        'evil dead',
        'resident evil 2',
      ],
      categoryId: '20',
      liveBroadcastContent: 'none',
      defaultLanguage: 'en',
      localized: {
        title: 'Dead By Daylight Parody 14 - Resident Evil (Animated)',
        description:
          "The Hookers plan their next move.\n\n►UPCOMING VIDS: https://bit.ly/2Qrdxky\n►JOIN SAMINATION: https://goo.gl/Xb18UC\n►DISCORD: https://discord.gg/un2gJFd\n►MERCH: https://teespring.com/stores/samination\n►TWITTER: http://www.twitter.com/saminating\n►INSTAGRAM: https://instagram.com/instasamination\n►PATREON: http://www.patreon.com/samination\n►SOUNDS/RINGTONES: https://samination.bandcamp.com\n\nSEND REAL MAIL TO:\nSam T Nelson\n9445 Coors Blvd NW @159\nAlbuquerque, NM 87114\n\n#samination #animation #parody\n\n0:00 Resident Leon\n1:09 Oh-No Mither\n1:57 Happy Anniversary\n2:46 Mean Plague\n3:31 Killer's Meeting\n4:53 Frank Mori's himself",
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: '7V1A1V6fM06jST-pO3ke7NUkCgY',
    id: 'QSq606ky4a8',
    snippet: {
      publishedAt: '2021-08-08T19:15:09Z',
      channelId: 'UCKqqDlf6lfo3ChRA4-gzusQ',
      title: 'DDG - Lusted (Official Video)',
      description: 'Stream "Lusted" on all streaming platforms.',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/QSq606ky4a8/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/QSq606ky4a8/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/QSq606ky4a8/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/QSq606ky4a8/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/QSq606ky4a8/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'DDG',
      tags: ['ddg', 'ddg music', 'ddg lusted', 'lusted', 'new ddg'],
      categoryId: '10',
      liveBroadcastContent: 'none',
      localized: {
        title: 'DDG - Lusted (Official Video)',
        description: 'Stream "Lusted" on all streaming platforms.',
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'eApGhHrszMJTeDo-MELR_tglj9Y',
    id: 'l-4ZBrhu8io',
    snippet: {
      publishedAt: '2021-08-08T22:45:42Z',
      channelId: 'UCqseWqrl7r-hNoWme7hIfTw',
      title: 'Real Things Said in Classrooms Pt. 20',
      description: '',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/l-4ZBrhu8io/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/l-4ZBrhu8io/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/l-4ZBrhu8io/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/l-4ZBrhu8io/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/l-4ZBrhu8io/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Rebecca Rogers (Mrs. Rogers)',
      tags: [
        'real',
        'real things',
        'real things said',
        'real things said in classrooms',
        'real things said in my classroom',
        'teacher',
        'student',
        'parent',
        'school',
        'classroom',
        'elementary school',
        'middle school',
        'high school',
        'creator',
        'conference',
        'karen',
        'seizure',
        '911',
        'dad',
        'mom',
        'teachers',
        'teachers of youtube',
        'youtube teacher',
        'tiktok',
        'tiktok teacher',
        'tiktok creator',
        'youtube creator',
        'viral',
        'funny',
        'story',
        'story time',
        'funny story',
        'go home',
        'annoying',
        'annoyed',
        'entitled',
        'Darren',
      ],
      categoryId: '23',
      liveBroadcastContent: 'none',
      localized: {
        title: 'Real Things Said in Classrooms Pt. 20',
        description: '',
      },
    },
  },
  {
    kind: 'youtube#video',
    etag: 'xEG5NlaxjeVx1vNqLvyEsxZ806U',
    id: '9tqDJw1OMo4',
    snippet: {
      publishedAt: '2021-08-08T11:15:45Z',
      channelId: 'UCNHqb1IRxQ5WBsWtO53JL2g',
      title:
        "'I am here to say goodbye': Lionel Messi tearful as Barcelona exit looms",
      description:
        "An emotional Lionel Messi has revealed he expected to extend his stay at Barcelona, but is now a free agent after financial issues at the Catalan club left them unable to pay the Argentinian’s wages. Speaking at his farewell press conference on Sunday morning, a tearful Messi said: 'This year, my family and I were convinced we were going to stay at home, that’s what we all wanted more than anything. We’d always made this our own, we were at home. We thought we would be staying here in Barcelona. But today, we have to say goodbye to all of this.'\n\nSubscribe to Guardian Football ► http://is.gd/GuardianFootball\n\n‘I wanted to stay’: Lionel Messi tearful at Barcelona exit as free transfer looms ► https://www.theguardian.com/football/2021/aug/08/lionel-messi-tearful-barcelona-transfer\n\nThe Guardian publishes independent journalism, made possible by supporters. Contribute to The Guardian today ► https://support.theguardian.com/contribute\n\nWebsite ► https://www.theguardian.com\nFacebook ► https://www.facebook.com/theguardian\nTwitter ► https://twitter.com/guardian\nInstagram ► https://www.instagram.com/guardian",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/9tqDJw1OMo4/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/9tqDJw1OMo4/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/9tqDJw1OMo4/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/9tqDJw1OMo4/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/9tqDJw1OMo4/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Guardian Football',
      tags: [
        'barcelona',
        'barcelona messi',
        'barcelona messi press conference',
        'barcelona news',
        'football',
        'gdnpfpsportfootball',
        'gdnpfpsportother',
        'lionel messi',
        'lionel messi barcelona',
        'lionel messi latest',
        'lionel messi news',
        'lionel messi press conference',
        'lionel messi psg',
        'messi',
        'messi crying',
        'messi final press conference',
        'messi goodbye',
        'messi leaves barcelona',
        'messi leaving barcelona',
        'messi tears',
        'messi to psg',
        'messi transfer latest',
        'messi transfer news',
        'messi farewell',
        'barca',
        'barcalona',
        'messi speech',
      ],
      categoryId: '17',
      liveBroadcastContent: 'none',
      localized: {
        title:
          "'I am here to say goodbye': Lionel Messi tearful as Barcelona exit looms",
        description:
          "An emotional Lionel Messi has revealed he expected to extend his stay at Barcelona, but is now a free agent after financial issues at the Catalan club left them unable to pay the Argentinian’s wages. Speaking at his farewell press conference on Sunday morning, a tearful Messi said: 'This year, my family and I were convinced we were going to stay at home, that’s what we all wanted more than anything. We’d always made this our own, we were at home. We thought we would be staying here in Barcelona. But today, we have to say goodbye to all of this.'\n\nSubscribe to Guardian Football ► http://is.gd/GuardianFootball\n\n‘I wanted to stay’: Lionel Messi tearful at Barcelona exit as free transfer looms ► https://www.theguardian.com/football/2021/aug/08/lionel-messi-tearful-barcelona-transfer\n\nThe Guardian publishes independent journalism, made possible by supporters. Contribute to The Guardian today ► https://support.theguardian.com/contribute\n\nWebsite ► https://www.theguardian.com\nFacebook ► https://www.facebook.com/theguardian\nTwitter ► https://twitter.com/guardian\nInstagram ► https://www.instagram.com/guardian",
      },
      defaultAudioLanguage: 'en-US',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'DUj5PopYUFR8mQVqrPCZ6CnqyOc',
    id: '28p9a6gw9Dk',
    snippet: {
      publishedAt: '2021-08-09T15:00:02Z',
      channelId: 'UCgFvT6pUq9HLOvKBYERzXSQ',
      title: 'Health',
      description:
        "Answering to serious questions about my health, bass, life. Also: beard\n\nSubscribe for more videos: https://goo.gl/G9As1e\nReddit: https://www.reddit.com/r/Davie504/\nPatreon: https://www.patreon.com/davie504\nMerch: https://represent.com/davie504\nTwitter: https://twitter.com/Davie504bass\nInstagram: https://www.instagram.com/davie504/\nFacebook: http://www.facebook.com/Davie504\nDiscord: https://discord.gg/davie504\n\nMy NEW ALBUM! \nSpotify: https://open.spotify.com/album/5m7SFVMTfNvv7dyqfa00G3\niTunes: http://itunes.apple.com/album/id1122291881?ls=1&app=itunes\n\nDon't forget to leave a comment to let me know if you enjoyed this video, it's important for me! :)\n\n If you want to be always updated about my channel, SUBSCRIBE! and JOIN THE FUNK! :D\n\nHope you'll like it!\n\nSee you soon and Stay Funky! :)",
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/28p9a6gw9Dk/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/28p9a6gw9Dk/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/28p9a6gw9Dk/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/28p9a6gw9Dk/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/28p9a6gw9Dk/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'Davie504',
      tags: ['davie504', 'bass', 'bass solo'],
      categoryId: '24',
      liveBroadcastContent: 'none',
      defaultLanguage: 'en',
      localized: {
        title: 'Health',
        description:
          "Answering to serious questions about my health, bass, life. Also: beard\n\nSubscribe for more videos: https://goo.gl/G9As1e\nReddit: https://www.reddit.com/r/Davie504/\nPatreon: https://www.patreon.com/davie504\nMerch: https://represent.com/davie504\nTwitter: https://twitter.com/Davie504bass\nInstagram: https://www.instagram.com/davie504/\nFacebook: http://www.facebook.com/Davie504\nDiscord: https://discord.gg/davie504\n\nMy NEW ALBUM! \nSpotify: https://open.spotify.com/album/5m7SFVMTfNvv7dyqfa00G3\niTunes: http://itunes.apple.com/album/id1122291881?ls=1&app=itunes\n\nDon't forget to leave a comment to let me know if you enjoyed this video, it's important for me! :)\n\n If you want to be always updated about my channel, SUBSCRIBE! and JOIN THE FUNK! :D\n\nHope you'll like it!\n\nSee you soon and Stay Funky! :)",
      },
      defaultAudioLanguage: 'en',
    },
  },
  {
    kind: 'youtube#video',
    etag: 'TteDSbO48EFHzb3QbQZ58ecVtOM',
    id: 'opA2cFIXDZ0',
    snippet: {
      publishedAt: '2021-08-08T16:45:02Z',
      channelId: 'UCFmhLDjF1bB6-rbv9TBqeQg',
      title: 'I Pretended to be Famous Streamers in Fortnite Fashion Shows...',
      description:
        'I Pretended to be Famous Streamers in Fortnite Fashion Shows by\nStealing Famous Youtubers Fortnite accounts and used their skin combos to compete in fortnite fashion shows! Rip Ninja, Lazarbeam, Lachlan, and Bugha...\n\nPre-Save The Song!  http://aries.lnk.to/kidsonmolly\nTalk to me ⤵️\n🔊 Join My Discord! https://discord.gg/DmkxjHE\n🥶 Follow My Twitter! https://twitter.com/Mileniooo\n\n❤️ Creator Code "milo" (ad)\n❤️ Subscribe to my 2nd Channel! @More Milo \n\n#milo #fortnite #fortnitefashionshow',
      thumbnails: {
        default: {
          url: 'https://i.ytimg.com/vi/opA2cFIXDZ0/default.jpg',
          width: 120,
          height: 90,
        },
        medium: {
          url: 'https://i.ytimg.com/vi/opA2cFIXDZ0/mqdefault.jpg',
          width: 320,
          height: 180,
        },
        high: {
          url: 'https://i.ytimg.com/vi/opA2cFIXDZ0/hqdefault.jpg',
          width: 480,
          height: 360,
        },
        standard: {
          url: 'https://i.ytimg.com/vi/opA2cFIXDZ0/sddefault.jpg',
          width: 640,
          height: 480,
        },
        maxres: {
          url: 'https://i.ytimg.com/vi/opA2cFIXDZ0/maxresdefault.jpg',
          width: 1280,
          height: 720,
        },
      },
      channelTitle: 'SoaR Milo',
      tags: [
        'fortnite fashion show',
        'fortnite',
        'fortnite battle royale',
        'fortnite fashion show live',
        'fortnite fashion shows',
        'stealing fortnite fashion shows',
        'live fortnite fashion show',
        'fortnite live fashion show',
        'fortnite skin combos',
        'stream sniped fortnite fashion shows',
        'ghoulz',
        'ghoulz fashion show',
        'milo',
        'soar milo',
        'stealing famous youtubers fashion show',
        'fashion show fortnite',
        'i stream sniped a fashion show',
        'rare skin fashion show',
        'pretending to be famous streamers in fortnite',
        'lachlan',
        'lazarbeam',
      ],
      categoryId: '20',
      liveBroadcastContent: 'none',
      localized: {
        title:
          'I Pretended to be Famous Streamers in Fortnite Fashion Shows...',
        description:
          'I Pretended to be Famous Streamers in Fortnite Fashion Shows by\nStealing Famous Youtubers Fortnite accounts and used their skin combos to compete in fortnite fashion shows! Rip Ninja, Lazarbeam, Lachlan, and Bugha...\n\nPre-Save The Song!  http://aries.lnk.to/kidsonmolly\nTalk to me ⤵️\n🔊 Join My Discord! https://discord.gg/DmkxjHE\n🥶 Follow My Twitter! https://twitter.com/Mileniooo\n\n❤️ Creator Code "milo" (ad)\n❤️ Subscribe to my 2nd Channel! @More Milo \n\n#milo #fortnite #fortnitefashionshow',
      },
    },
  },
];
